services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: always
    volumes:
      - /mnt/docker-data/security/authelia:/config
    ports:
      - "9091:9091"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - dockernet

networks:
  dockernet:
    external: true